---
- hosts: web
  become: yes
  tasks:
    - name: Build docs
      ansible.builtin.shell:
        cmd: yarn build:docs
        chdir: ../
      delegate_to: localhost
      timeout: 5
    - name: Publish docs
      copy:
        src: ../dist/apps/docs
        dest: "{{docs_dir}}"
      tags: publish-docs
