---
- hosts: web
  tasks:
    - name: Build docs
      community.general.yarn:
        cmd: build:docs
        chdir: ../
      delegate_to: localhost
      timeout: 5
    - name: Publish docs
      copy:
        src: ../dist/apps/docs
        dest: "{{docs_dir}}"
